# Inspiration: https://github.com/OpenMRBenelux/openmr2021-dataviz-workshop/blob/main/binder/environment.yml

name: FLightcase

channels:
  - default
  - conda-forge

dependencies:
  - python=3.11.*
  - pip=24.2
  - git=2.45.2
  - git-annex=10.20230626
  - datalad=1.1.4
  - datalad-installer=1.1.1

  - pip:
      - torch==2.5.1
      - pandas==2.2.3
      - monai==1.4.0
      - scikit-learn==1.6.0
      - tqdm==4.67.1
      - nibabel==5.3.2
      - paramiko==3.5.0
      - scp==0.15.0
      - matplotlib==3.10.0
      - scipy==1.14.1
      - numpy==1.26.4  # 2.2.0 causes conflict with monai==1.4.0
      - click==8.1.8